// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5GdEb9xJto_DYJIaRBttQLwLFoIpumU',
    appId: '1:898582489266:web:905b2ab42744a974c941ab',
    messagingSenderId: '898582489266',
    projectId: 'bisente-advmobprog-firebase',
    authDomain: 'bisente-advmobprog-firebase.firebaseapp.com',
    storageBucket: 'bisente-advmobprog-firebase.firebasestorage.app',
    measurementId: 'G-24X2MZS2W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPQv3wbuSqQcqNfXnbclMHtf8MFv19oE',
    appId: '1:898582489266:android:a786825e047c78aec941ab',
    messagingSenderId: '898582489266',
    projectId: 'bisente-advmobprog-firebase',
    storageBucket: 'bisente-advmobprog-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxAl--_BDZUJRmc3b8Q_PBNCoFtf9Xhc',
    appId: '1:898582489266:ios:a8352451dce9d930c941ab',
    messagingSenderId: '898582489266',
    projectId: 'bisente-advmobprog-firebase',
    storageBucket: 'bisente-advmobprog-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxAl--_BDZUJRmc3b8Q_PBNCoFtf9Xhc',
    appId: '1:898582489266:ios:a8352451dce9d930c941ab',
    messagingSenderId: '898582489266',
    projectId: 'bisente-advmobprog-firebase',
    storageBucket: 'bisente-advmobprog-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj5GdEb9xJto_DYJIaRBttQLwLFoIpumU',
    appId: '1:898582489266:web:585b1508120ecc33c941ab',
    messagingSenderId: '898582489266',
    projectId: 'bisente-advmobprog-firebase',
    authDomain: 'bisente-advmobprog-firebase.firebaseapp.com',
    storageBucket: 'bisente-advmobprog-firebase.firebasestorage.app',
    measurementId: 'G-YZRY6KLEFQ',
  );
}
